### ISSUE TITLE
ITPS Response Files

### ISSUE THREAD

**Issue by courtneycorwin** [GSA/ITDB-schema#357]
In the response files agencies are getting back for the ITPS validation, the UII an error is related to isn't returned.  Just a line number.  Can the UII be included in the error message?

**Comment by mayuri-khatri** [comment]
Hi Courtney,

We want to follow up on this thread, as this was discussed verbally during the CPIC Vendor Meeting on 8/20 (and a subsequent email thread since that). As we discussed, this update would require a code change, which is not feasible given the current ITDB Development schedule. It will be added to the backlog for potential Product Owner prioritization as a part of future modernization efforts.
Please let us know if you have any further questions.

Thank you,
ITDB Support

**Comment by courtneycorwin** [comment]
Hi All,

I'm absolutely fine with that.  The subsequent emails you received where not on my behalf.  I'll close this ticket.

Thanks!
Courtney
