### ISSUE TITLE
CIO Evaluation Report Warning

### ISSUE THREAD

**Issue by courtneycorwin** [GSA/ITDB-schema#388]
Hi All,

When submitting CIO Evaluation Reports for an SIR (which I believe is required for the BY21 submission), a couple of agencies have reported getting a warning message that the report is only required for Majors.  

This isn't a huge deal since they are still able to be submitted, but does this mean the report isn't being checked by the Submission Confirmation?

**Comment by samanthathomas20** [comment]
Hi Courtney,

Thanks for reaching out. Per the OMB Guidance document, CIO Evaluations are required for all Major investments and SIRs.

However, OMB has agreed to relax the validation implementation (from our understanding, to account for one-off investments that may not have a valid CIO Evaluation to submit). As a result, the message that your agencies are receiving says that only Major investments are required. From our insight, OMB’s expectations about which investments are submitting this data has not changed from what is detailed in the Guidance. If you have questions about not submitting this data for specific Majors or SIRs, our recommendation is to reach to your OMB Desk Officer.

One additional note to pass along. Based on the current implementation, the ITDB will only generate this warning if you have not submitted a CIO Rating for a "required" investment (Major or SIR). However, since this is confusing wording on this warning and it provides limited value to agencies, we will be removing it in our next deployment, which will be sometime this week.

Thanks,
Sam
ITDB Support

**Comment by courtneycorwin** [comment]
Ok - I'll let agencies know the validation was relaxed.  Agencies are getting this warning in response to submitting a CIO Rating for an SIR, so I think your statement "Based on the current implementation, the ITDB will only generate this warning if you have not submitted a CIO Rating for a "required" investment (Major or SIR)" might be in error.

**Comment by mayuri-khatri** [comment]
Hi Courtney,

We wanted to let you know that the misleading CIO Evaluation warning has been removed from the dashboard.

Please let us know if you have any questions.

Regards,
Mayuri
ITDB Support

**Comment by courtneycorwin** [comment]
Thanks!
